[package]
name = "gdrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
bio = "1.5.0"

[dev-dependencies]
rstest = "0.18.2"
